### ISSUE TITLE
Macro

### ISSUE THREAD

**Issue by cnutenor** [davelens/fvtt-party-resources#19]
Hi, im try to create a macro to open party resources.

Like this
if (Party Resources.window.rendered)
  Party Resources.close();
else 
  Party Resources.(true);

Can you help me?

**Comment by davelens** [comment]
@cnutenor Ah, I already responded to you in Discord just now. I'll put my reply here just in case anyone stumbles upon this.

You can access the dashboard modal with `window.pr.dashboard`.

```js
window.pr.dashboard.rendered ? window.pr.dashboard.close() : window.pr.dashboard.render(true)
```
