### ISSUE TITLE
Player Control

### ISSUE THREAD

**Issue by fighterchimp** [davelens/fvtt-party-resources#2]
The ability for players to edit the resources and/or add new ones would be cool, less overhead for the GM. Keeping track of everything in a system with lots of stuff like that gets pretty time-consuming.

**Comment by davelens** [comment]
@fighterchimp Hi! Thank you for your comment and sorry for the tardy response. In all honesty, I missed the notification apparently.

* Having players edit the resources: This is something I'd like to get done. To my knowledge, there's two ways to go about this:
  1. A global toggle ("Can players edit this resource?") would be fairly easy to implement, but limits permissions to "all players" or "gm-only".
  2. Using Foundry's Permissions functionality would allow for player-specific permission settings per resource. As of yet, I'm unfamiliar with how I'd go about this, though I'm sure I could figure it out looking at other modules. Therefore, the main factor here is time.
* Having players add resources: Do you mean player-specific, and therefore private, resources to track? I guess this would be partially solved by tackling permission settings per resource, as well.

**Comment by fighterchimp** [comment]
haha, i've missed plenty of notifications in my day too! it's no problem at all. 

for the system i'm running, a simple global toggle for player control would be sufficient, players wouldn't need the ability to add their own. i know very little about javascript, but i could try looking into how to do that.

**Comment by davelens** [comment]
@fighterchimp So I've done some work on this and I've hit a bump in the road. You can read up on it in PR #3 

I'm fairly sure I'll figure something out, but I have no timeline currently. :-/

**Comment by fighterchimp** [comment]
hmm, that's an interesting issue. i'm sure you'll figure something out too! thank you for looking into the option. i wish i could offer more help, but this seems like the kind of code that's totally beyond me, haha

**Comment by davelens** [comment]
@fighterchimp #3 is now merged into the master branch. It's not the extended (or "proper") solution for this problem, but it's a solution nonetheless. It will be included in the 1.1 release, but you're free to pull from the master branch if you want to test it out locally.

There *might* be an issue with pre-existing data, but I'll have that confirmed between now and the next release.

**Comment by fighterchimp** [comment]
hey, i'm not sure if i'm missing something, but i can't seem to give players the ability to edit a resource. the checkbox that gives the option is greyed out, and when i hit the box that says "configure player permissions" it brings me to the module settings window - but there's no section for party resources there that would allow me to give players the ability.

**Comment by davelens** [comment]
> it brings me to the module settings window - but there's no section for party resources there that would allow me to give players the ability.

In the settings window, click the `Open Permission Configuration` button at the top:
![pr-settings-1](https://user-images.githubusercontent.com/221527/101842595-b11bb800-3b48-11eb-8c05-810d53564205.jpg)

In the resulting window, check the checkbox below the `Player` column here:
![pr-settings-2](https://user-images.githubusercontent.com/221527/101842502-79ad0b80-3b48-11eb-9554-3dd4057589f0.jpg)

Click the `Save Configuration` button at the bottom, and you should be set!

**NOTE**: If the resource form is still open in the background at this point, you'll need to close and reopen it in order to make the checkbox available. The form doesn't refresh itself automatically after the settings have been updated.
