### ISSUE TITLE
Add a small status bar somewhere to provide a better overview of resource values.

### ISSUE THREAD

**Issue by davelens** [davelens/fvtt-party-resources#21]
Think resource bars at the top/bottom of the screen in games like Civilization or Age of Empires.

Should use both text and any assigned icon images, and should be togglable through Foundry's module settings.

**Comment by TheMathKing** [comment]
This would be amazing. Let us pray to the coding gods.

**Comment by irbian** [comment]
In this line, it would be nice to have only the status bar, so the players don´t know how much exactly they have (for things as diffuse as "army strength")

**Comment by davelens** [comment]
Closing this, as the first version of this got merged. For specific feature requests, please create a new issue.
