### ISSUE TITLE
Make it possible to track some pre-existent resources like gold.

### ISSUE THREAD

**Issue by davelens** [davelens/fvtt-party-resources#23]
When adding a resource, add a "link existing resource" with a dropdown of choices to the resource form. The obvious first option would be "gold", which counts all gold across the party and displays a total as a resource. Not sure which other resources I could track yet (hitpoints current/max totals?).

Note that I can't make it that when you add a resource and you call it "gold", it'd set this tracking up automatically because that would screw existing installs out of their values.

**Comment by Pantong51** [comment]
I'd also know to know how to do this for things like rations

**Comment by davelens** [comment]
@Pantong51 Gold and rations will be the first two resources that get shipped with this feature, once I get to work on it. This is also dependent on how Foundry registers those item types.

**Comment by davelens** [comment]
So what's important to remember about this is that Party Resources is (unintentionally, but here we are) system agnostic, and "currency" as a concept is not present in every game system. 

dnd5e happens to have currency, and I will start out supporting that. Any other gaming system (sw-ffg, warhammer,...) will have to be reviewed to see if I can grab changes through `updateActor` as well.

**Comment by davelens** [comment]
You can track the status for this feature in #52.

**Comment by davelens** [comment]
PR #52 is now functional. It will allow you to add both D&D 5e gold and rations as trackable resources, providing you with a sum of all values across all player characters. I'll be merging this tomorrow evening, after I've been able to do some more testing.

**Comment by davelens** [comment]
> PR #52 is now functional. It will allow you to add both D&D 5e gold and rations as trackable resources, providing you with a sum of all values across all player characters. I'll be merging this tomorrow evening, after I've been able to do some more testing.

So the good news is this PR is almost done *and* I've found a way to not be limited to just gold and rations. As it stands, any item will be able to be tracked by its name. So this means rations, potions of healing, arrows,... will all be possible to track across the player characters' inventories.

The bad news is, I can't merge today yet. There's two particular problems I need to solve before I'm able to merge it, one of which will impact how easy it will be to extend the functionality to other game systems.

Keep you posted!

**Comment by davelens** [comment]
This got merged and released in 1.5.0. You can now track dnd5e's gold and any dnd5e item(s) by name (even multiple items into one tracker). @Pantong51 I know it's been a while, but this includes the rations you mentioned.

I'm willing to look into other systems if there's interest in them.
