### ISSUE TITLE
Players unable to manage resources. 

### ISSUE THREAD

**Issue by TheMathKing** [davelens/fvtt-party-resources#27]
I have enabled "Allow players to manage this resource." for all my resources but when players try to do so it says "User <name> lacks permission to update Setting[<some reference>]".

Any idea why this is the case? 

I am running the latest version of the module and version 0.8.7 of foundry

**Comment by davelens** [comment]
@TheMathKing I'll give it a look once I'm back from my holiday. Last time I checked this was in 0.8.6 and it seemed to be working fine, but I'll double check in 0.8.7.

**Comment by TheMathKing** [comment]
> @TheMathKing I'll give it a look once I'm back from my holiday. Last time I checked this was in 0.8.6 and it seemed to be working fine, but I'll double check in 0.8.7.

I am now updated to 0.8.8 and it still does not let players or  trusted players manipulate the resources (I haven't tried co-dms)

**Comment by davelens** [comment]
@TheMathKing I just tried this in a fresh Foundry 0.8.8 install (and assuming DND 5e), but it seems to be working as intended. I'm guessing the actor's data is corrupted in some way or another, or there's a conflict with another module.

Can you confirm the checkbox for "Player" is checked, like in the following screenshot?
![fvtt-8](https://user-images.githubusercontent.com/221527/127648820-27c6a128-02e8-4ae6-bc8b-aa9f31f4a7c2.png)

**Comment by TheMathKing** [comment]
> @TheMathKing I just tried this in a fresh Foundry 0.8.8 install (and assuming DND 5e), but it seems to be working as intended. I'm guessing the actor's data is corrupted in some way or another, or there's a conflict with another module.
> 
> Can you confirm the checkbox for the "Player" column is checked, like in the following screenshot?
> ![fvtt-8](https://user-images.githubusercontent.com/221527/127648820-27c6a128-02e8-4ae6-bc8b-aa9f31f4a7c2.png)

Yup that was it. I was sure I enabled everything for my "trusted players", this must have been a new option that I didn't pick up on. Sorry to waste your time.
