### ISSUE TITLE
Player can...

### ISSUE THREAD

**Issue by Ulvtand** [davelens/fvtt-party-resources#29]
Players can add resources

**Comment by davelens** [comment]
@Ulvtand I'm probably going to need some more information here, as I'm not sure what your statement implies. Here are a few quick answers depending on the intent of your comment:

* If your players can see the add/edit resource buttons on the dashboard, it would mean they have Gamemaster rights.
* If it's a question, then no, players currently cannot add resources themselves unless they are made Gamemasters.
* If this is a request to allow players to add resources themselves, then I'll have to disappoint and say that's not a change I'm currently considering.

**Comment by davelens** [comment]
> Such a shame :)

@Ulvtand I understand. The intent of the module was always to have a way for game/dungeon masters to keep track of simple numeric values, and for players to see them update in real time. The compromise I made there is to build in a way to allow players to manage resources. Having players create them freely would go beyond the scope of its current design, meaning I'd have to rewrite a sizable chunk of code.

**Comment by Ulvtand** [comment]
I understand, but this is the only standalone module of its kind (what I have been able to find). So I think it will be more popular if the players can also add. ;)
