### ISSUE TITLE
v9

### ISSUE THREAD

**Issue by brunocalado** [davelens/fvtt-party-resources#30]
Hi.

Please remove the foundry vtt warning.

Replace "compatibleCoreVersion":"0.9.0" by "compatibleCoreVersion":"9".

Docs: https://gitlab.com/foundrynet/foundryvtt/-/issues/5635

**Comment by davelens** [comment]
@brunocalado I had not yet tested v9 myself until I finally came around to it today. Originally, the plan was to push the v9 update along with a couple of features, but Covid made sure this wasn't meant to be. I can understand this version mismatch can be annoying, so the update to the compatible core version was pushed in the 1.2.5 tag.

Happy gaming!

**Comment by brunocalado** [comment]
tks
