### ISSUE TITLE
Party Resources button does not appear under actors tab after updating to v9

### ISSUE THREAD

**Issue by TheMathKing** [davelens/fvtt-party-resources#31]
I have reinstalled the module and it still does not appear. It's fully installed too.

**Comment by davelens** [comment]
@TheMathKing It sounds like there are other errors occuring that prevent the module from loading in general.

Could you check if there are any errors in the Javascript console? (F12 in Firefox/Chrome, or if you run Foundry as an app you can find it in the menu. It's called "Developer console" or something, I can't double check since I'm on mobile atm).

**Comment by TheMathKing** [comment]
I ended up reinstalling FoundryVTT and it ended up working. My issue now is
that the status bar will not show up at the top of the screen. When I click
"save changes" to enable it I get this error:

foundry.js:3856 TypeError: Cannot read properties of undefined (reading
'redraw')    at Setting._onUpdate (foundry.js:18103)    at
ClientDatabaseBackend.callback (foundry.js:10260)    at foundry.js:10212
 at Array.map (<anonymous>)    at
ClientDatabaseBackend._handleUpdateDocuments (foundry.js:10212)    at
ClientDatabaseBackend._updateDocuments (foundry.js:10093)    at async
Function.updateDocuments (document.mjs:373)    at async Setting.update
(document.mjs:456)    at async ClientSettings.set (foundry.js:2202)    at
async ExtendedSettingsConfig._updateObject (foundry.js:55538)    at async
ExtendedSettingsConfig._onSubmit (foundry.js:3853)

**Comment by davelens** [comment]
@TheMathKing That's something that slipped into master when it shouldn't have yet. I just merged the status bar into master and made a new release, should be fixed now.

**Comment by davelens** [comment]
@TheMathKing I'm assuming this one got resolved, based on the error message above. If not, do comment back and I'll reopen.
