### ISSUE TITLE
[Feature Request/Enhancement] Different notifications depending on whether the resource value is increased or decreased

### ISSUE THREAD

**Issue by Krigsmaskine** [davelens/fvtt-party-resources#32]
Hi,

In games where it's important to keep things lower (or higher) such as tracking madness or oxygen, it'd be great if there could be separate kinds of notifications for resources when decreasing vs. increasing, since one is often preferable to the other and the message adds a lot of gravitas to the change.

Regardless, thanks for the module, really useful for maddening tabletops!

**Comment by davelens** [comment]
@Krigsmaskine Hi! Thanks for the feedback. This is something I agree with, and will probably end up adding this to the module when I get to fiddle with the notifications. As always I don't have an ETA, but I've marked it as an enhancement and it'll be in one of the next updates, after #33 gets merged.

**Comment by davelens** [comment]
@Krigsmaskine This feature was added and will be released in 1.3.2 (ETA unknown, but somewhere within the next two weeks, more than likely).

**Comment by davelens** [comment]
@Krigsmaskine The feature you requested was added in in the latest release. It's a major release instead, 1.4.1. Happy DM'ing!
