### ISSUE TITLE
Add French translation

### ISSUE THREAD

**Issue by sladecraven** [davelens/fvtt-party-resources#35]
Hi !
fr.json file provided here, 

Thanks !
`
{
  "FvttPartyResources.Dashboard.AddButtonTitle": "Augmenter la quantité",
  "FvttPartyResources.Dashboard.BlankWarning": "Les blocs de ressources apparaitront uniquement une fois ajoutés.",
  "FvttPartyResources.Dashboard.DeleteButtonTitle": "Supprimer la ressource",
  "FvttPartyResources.Dashboard.EditButtonTitle": "Editer la ressource",
  "FvttPartyResources.Dashboard.MakeInvisibleButtonTitle": "Cacher cette ressource aux joueurs",
  "FvttPartyResources.Dashboard.MakeVisibleButtonTitle": "Afficher cette ressource aux joueurs",
  "FvttPartyResources.Dashboard.SubtractButtonTitle": "Soustraire la quantité",
  "FvttPartyResources.FirstTimeNotification": "Bienvenu à <strong>Party Resources v{version}</strong>!<br>Si c'est la première fois que vous utilisez ce modile<br>suivez ce lien pour être guidé : {anchor}.",
  "FvttPartyResources.ResourceForm.AddFormTitle": "Ajouter une nouvelle ressource",
  "FvttPartyResources.ResourceForm.AllowPlayersToModifySettings": "Permettre aux joueurs de modifier la configuration",
  "FvttPartyResources.ResourceForm.CreateResource": "Créer une ressource",
  "FvttPartyResources.ResourceForm.DefaultValue": "Valeur par défaut",
  "FvttPartyResources.ResourceForm.DefaultValueHint": "La valeur initiale de la ressource.",
  "FvttPartyResources.ResourceForm.EditFormTitle": "Editer la ressource",
  "FvttPartyResources.ResourceForm.Headers.Label": "Nom",
  "FvttPartyResources.ResourceForm.Headers.Notifications": "Notifications",
  "FvttPartyResources.ResourceForm.Headers.Settings": "Configuration",
  "FvttPartyResources.ResourceForm.Headers.Values": "Valeurs",
  "FvttPartyResources.ResourceForm.IconImage": "Chemin de l'icone",
  "FvttPartyResources.ResourceForm.Identifier": "ID de la ressource",
  "FvttPartyResources.ResourceForm.IdentifierHint": "L'identifiant qui représent la ressource dans l'API. Ne doit pas contenir d'espaces ou de chiffres, and uniquement en minuscules.",
  "FvttPartyResources.ResourceForm.MaxValue": "Valeur maximum",
  "FvttPartyResources.ResourceForm.MaxValueHint": "Lorsque cette valeur (optionnelle) est renseignée, vous ne pourrez pas incrémenter la ressource au dessus de cette valeur.",
  "FvttPartyResources.ResourceForm.MinValue": "Valeur minimum",
  "FvttPartyResources.ResourceForm.MinValueHint": "Lorsque cette valeur (optionnelle) est renseignée, vous ne pourrez pas décrémenter la ressource en dessous de cette valeur.",
  "FvttPartyResources.ResourceForm.Name": "Nom de la ressource",
  "FvttPartyResources.ResourceForm.NameHint": "Le nom affichée dans la barre de ressources.",
  "FvttPartyResources.ResourceForm.NotifyChat": "Notifier les joueurs des changements de valeur",
  "FvttPartyResources.ResourceForm.NotifyChatHint": "Affiche un message dans le tchat quand la ressource change de valeur.",
  "FvttPartyResources.ResourceForm.NotifyChatMessage": "Message de tchat",
  "FvttPartyResources.ResourceForm.NotifyChatMessageHint": "Le message affiché dans le tchat lorsqu'une valeur change.",
  "FvttPartyResources.ResourceForm.PlayerManaged": "Autoriser les joueurs à gérer cette ressource.",
  "FvttPartyResources.ResourceForm.PlayerManagedHint": "Activer ce choix permettra aux joueurs de changer la valeur de la ressource.",
  "FvttPartyResources.ResourceForm.PlayerManagedRestriction": "Cette checkbox peut seulement être activé en autorisant les joueurs à modifier la configuration.",
  "FvttPartyResources.ResourceForm.Reset": "Reset du formulaire",
  "FvttPartyResources.ResourceForm.SaveChanges": "Sauvegarder les changements",
  "FvttPartyResources.ResourceForm.UseIcon": "Utiliser une icone au lieu d'un nom de ressource.",
  "FvttPartyResources.GMSettingsForm.IconImagesOrientation": "Change l'apparence de l'image d'icône.",
  "FvttPartyResources.GMSettingsForm.IconImagesOrientationBelow": "Texte en dessous de l'icone",
  "FvttPartyResources.GMSettingsForm.IconImagesOrientationHint": "Affecte la manière dont les images sont affichées dans la barre des ressources. Vous pouvez afficher un texte au dessus de l'icone, ou bien avoir le texte aligné en dessous de l'icone.",
  "FvttPartyResources.GMSettingsForm.IconImagesOrientationOnTop": "Texte au dessus de l'icone",
  "FvttPartyResources.GMSettingsForm.ShowActorsButtonForPlayers": "Afficher le bouton des Ressources de Groupe.",
  "FvttPartyResources.GMSettingsForm.ShowActorsButtonForPlayersHint": "Lorsque décoché, les joueurs ne verront plus le bouton des Ressources de Groupe en haut des Acteurs. Seulement le MJ peut le voir et l'utiliser.",
  "FvttPartyResources.GMSettingsForm.ShowStatusBar": "Afficher la barre de statut.",
  "FvttPartyResources.GMSettingsForm.ShowStatusBarHint": "Affiche une barre de statut en haut de l'écran, en affichant la valeur courante de chaque ressource.",
  "FvttPartyResources.GMSettingsForm.StatusBarLocation": "Change la position de la barre de statut",
  "FvttPartyResources.GMSettingsForm.StatusBarLocationHint": "Détermine à quel endroit la barre de statut est affichée.",
  "FvttPartyResources.GMSettingsForm.StatusBarLocationAtBottom": "En bas",
  "FvttPartyResources.GMSettingsForm.StatusBarLocationOnTop": "En haut",
  "FvttPartyResources.Title": "Ressources de Groupe"
}
`

**Comment by davelens** [comment]
@sladecraven Thank you for the translation file, it's included in today's release (1.2.8).
