### ISSUE TITLE
Feature : dynamic display of the ressources  status bar (with a macro function)

### ISSUE THREAD

**Issue by sladecraven** [davelens/fvtt-party-resources#36]
Allow the option to dynamically show()/hide() the status bar for all players/GM at the same time.
Useful when you want to show party resources only during particular scenes/sequences.

**Comment by sladecraven** [comment]
Hi !
Do you plan to do something on this ?

**Comment by davelens** [comment]
@sladecraven This can be done through a script macro and the little API that comes with Party Resources. Here are the commands to hide/show the status bar:

Hiding:
```js
window.pr.api.set('toggle_status_bar', false)
```

Showing:
```js
window.pr.api.set('toggle_status_bar', true)
```

**Comment by sladecraven** [comment]
Yes, but as far as I know, it does not cascade the hide information to other players. 
My idea is to have a controlled view by the GM only, to display/hide when he decides to.

**Comment by davelens** [comment]
> as far as I know, it does not cascade the hide information to other players.

@sladecraven That would be incorrect, the API commands do cascade their values through to everyone connected to the foundry instance. All settings Party Resources creates are Foundry world settings, meaning their values automatically persist to everyone in real time.

It's "one size fits all though", so no separate toggles for players or gms.

**Comment by sladecraven** [comment]
Ok, thanks, I will test again; because last time I did, the status bar was not hidden on player side, only GM side.

**Comment by sladecraven** [comment]
OK, tested, it works!
