### ISSUE TITLE
[Feature request] Aproximation bar

### ISSUE THREAD

**Issue by irbian** [davelens/fvtt-party-resources#40]
Hi!

We sometimes have resources where we want to show an approximate idea of the resource, but not exact numbers, like a loading bar, the life of the final boss, how much is filled the holy water container... Could be done?

**Comment by davelens** [comment]
@irbian Interesting. I suppose it'd be technically possible to show a small green bar in both the status bar and the dashboard, based on how far along a value is in regards to its maximum.

I'll park it as an enhancement for a later update for now.

**Comment by davelens** [comment]
@irbian I'll be closing this in favour of #42, as that will provide the functionality you requested.
