### ISSUE TITLE
[Feature Request] Option to change the Amount that is added or decreased to a resource with one Klick

### ISSUE THREAD

**Issue by V3rotti** [davelens/fvtt-party-resources#41]
An option to let you incrase or decrease the resource by n with one Klick at "+" or "-".

**Comment by davelens** [comment]
@V3rotti I'm not sure if this is the same as what you mean, but the readme says you can currently do this as you click on the + or - buttons:
> Increment/decrement resource values
> - Hold CTRL (Windows) or CMD (MacOS) when clicking to jump by +/- 10
> - Hold SHIFT when clicking to jump by +/- 100

**Comment by V3rotti** [comment]
uh yeah, i didn't know that! For me that fits my needs perfectly.

**Comment by davelens** [comment]
> uh yeah, i didn't know that! For me that fits my needs perfectly.
@V3rotti Great! 🙂 Closing this
