### ISSUE TITLE
Escape closes Party Resources Window

### ISSUE THREAD

**Issue by Craftzero** [davelens/fvtt-party-resources#43]
There are times in the thick of battle, when I need to hit Escape to clear out various targets I have or for other reasons.  Unfortunately, this also closes the Party Resources window.  Is there any way we can have it not close the window?

**Comment by davelens** [comment]
The PR dashboard window is a bog standard Foundry `Application` window, which means any events linked to it (like closing it through pressing ESC) are Foundry's default.

I'll have to ask around on the Discord to see if it's possible to override said events without destroying the default behaviour for other `Application` windows. When I know more, I'll post it here.

**Comment by davelens** [comment]
As a little update: Currently asking around on the Discord again, as I didn't get much reaction last time. Foundry 10 just released as well, so I'll be giving it a look if something changed in regards to events on existing `Application` windows. Last time I tried to force this, I accidentally disabled the ESC for all windows and couldn't seem to get it right to work just for PR's window.

**Comment by davelens** [comment]
@Craftzero One of the community members informed me about this:

> Foundry doesn't give enough signaling for anything but overriding .close() to work.

Which basicly means that yes, I can cancel the closing of the window, but I have no other means of closing the window beyond that. So I can't both cancel "pressing ESC" and keep "manually clicking the close button". You'd end up with a perpetually open dashboard.

I'll close this until further notice (i.e. we can exert more control over Foundry's defaults). Sorry!
