### ISSUE TITLE
Chat message doesn't appear

### ISSUE THREAD

**Issue by Ksen01** [davelens/fvtt-party-resources#44]
Hello,
I have an issue with chat message option. When i check this button my comment never appear with with message about value change. Am I doing something wrong or is it just not working at the moment?

**Comment by Ksen01** [comment]
![1](https://user-images.githubusercontent.com/42182727/171767347-0ab9f08b-b44f-4a07-b350-0570f13236d3.png)
![2](https://user-images.githubusercontent.com/42182727/171767351-e52ffb31-20fa-4c13-86ce-4f734d4b5b17.png)

**Comment by davelens** [comment]
@Ksen01 Hi, sorry for the delay in getting back to you. I can confirm this to be a bug in the module, though I don't know what's causing it yet. Will be fixed in the next release.

**Comment by davelens** [comment]
@Ksen01 Hi, I wanted to update you after a long bout of nothing (life, basically). I have time planned to get this fixed this week. Expect a release the coming weekend.

Thanks again for taking the time to report it!

**Comment by Ksen01** [comment]
Thanks for you work!

**Comment by davelens** [comment]
@Ksen01 This is now fixed in 1.2.9. Happy DM'ing!
