### ISSUE TITLE
Macro for increasing an decreasing

### ISSUE THREAD

**Issue by Zamino** [davelens/fvtt-party-resources#46]
Hi there,
could you please make a macro code available for increasing and decreasing resources. Maybe something like

To add 1 value: window.pr.api.add('resourceA', 1, { notify: true })

**Comment by davelens** [comment]
> Hi there, could you please make a macro code available for increasing and decreasing resources. Maybe something like
> 
> To add 1 value: window.pr.api.add('resourceA', 1, { notify: true })

@Zamino This already exists, but I didn't include these in the FAQ (until now):

> To increment the value of the fate resource by 2:
> ```js
> window.pr.api.increment('fate', 2)
> ```

> To decrement the value of the fate resource by 1:
> ```js
> window.pr.api.decrement('fate', 1)
> ```

**Comment by Zamino** [comment]
great! Thank you
