### ISSUE TITLE
Settings do not open

### ISSUE THREAD

**Issue by kagedansa** [davelens/fvtt-party-resources#47]
With the module activated i can not open settings anymore.

![error](https://user-images.githubusercontent.com/110729103/188600597-244485d1-fec7-4ab5-abb8-ba95693584e4.png)

**Comment by davelens** [comment]
@kagedansa It's an issue with the Settings Extender module, which Party Resources requires to function properly. You can read up on it [here](https://gitlab.com/foundry-azzurite/settings-extender/-/issues/10). According to its dev, it should be fixed either later today, or tomorrow.

**Comment by davelens** [comment]
@kagedansa Azurrite released the v10 update for Settings Extender around 5 hours ago. Update that module and the menu should be accessible again.
