### ISSUE TITLE
foundry hud weblate

### ISSUE THREAD

**Issue by eunaumtenhoid** [davelens/fvtt-party-resources#53]
hi, is it possible to add your mods to foundry hud weblate for us to translate or update the translation faster? https://weblate.foundryvtt-hub.com/

**Comment by davelens** [comment]
@eunaumtenhoid Hi, I've actually already sent a request to add the module, but haven't heard back from them yet. Currently awaiting response and I'll see what needs to be done to make it work.

**Comment by eunaumtenhoid** [comment]
tks!

**Comment by davelens** [comment]
I received a notification that they set up stuff on their end, with instructions for me to link my repo. It's a webhook I need to configure essentially, will happen somewhere in the next week +/-.

**Comment by davelens** [comment]
@eunaumtenhoid Weblate is now configured, and you'll find the project's page [here](https://weblate.foundryvtt-hub.com/engage/party-resources/). I added a dutch translation by means of testing it out, seems to work just fine!
