### ISSUE TITLE
Players cannot update with box checked

### ISSUE THREAD

**Issue by cbgh2021** [davelens/fvtt-party-resources#64]
I've tried to set up a bunch of resources for my players to track. Does not work. Keeps telling them they don't have permission.

**Comment by cbgh2021** [comment]
Nevermind

**Comment by davelens** [comment]
For people in the future browsing through the issues for similar problems: Double check the following checkbox in the resource's form. You need to explicitly allow players to modify configuration settings, then check the relevant checkbox before they can change a resource's values themselves:

<img width="596" alt="fvtt-pr-settings" src="https://user-images.githubusercontent.com/221527/205298343-5bf74b53-ce70-4311-8b9e-56de93b62d92.png">
