### ISSUE TITLE
Default values

### ISSUE THREAD

**Issue by plaasmaandraax** [davelens/fvtt-party-resources#65]
ResourcesApi.register_setting(name, options) and ModuleSettings.static register() should have empty as default value

**Comment by davelens** [comment]
@plaasmaandraax I don't think I understand what you're trying to say. If you're referring to the default values that get passed into `game.settings.register()` from the methods you mentioned, then I believe these to be valid as is?

**Comment by davelens** [comment]
Closing this until further notice.

**Comment by plasmaboyer** [comment]
I get some bugs without these defaut values, in my specific case. I can't remember which ones today, but I define them explicitly

<img width="368" alt="image" src="https://user-images.githubusercontent.com/278798/214044180-8c01cfec-50ca-454b-8ad2-825565bb94c8.png">

<img width="515" alt="image" src="https://user-images.githubusercontent.com/278798/214044404-a5ce61ee-b88c-4dea-8aca-e39b2a15e004.png">
