### ISSUE TITLE
Feature Request: Negative resource values

### ISSUE THREAD

**Issue by megahead11** [davelens/fvtt-party-resources#7]
At the moment, the party resource value can be no lower than 0. For specific things, like say a "Karma" system or faction reputation system, where you might want values to be negative (or any other applicable case), being able to reduce the value below 0 would be nice. 
Ideally, 0 should only be a limit for resources without a maximum, but I could see this also working as a universal toggle for the resource.

**Comment by davelens** [comment]
@megahead11 When I was initially working on this I was contemplating if I'd ever need negatives, but couldn't come up with a good example. Even though one of my games is now running with a fame level they could go in the red with, it didn't occur to me to put it in.

This shouldn't be a big change and it makes sense on all counts. I don't have a time frame, but I'll add it in the next release. Thanks for your request!

**Comment by davelens** [comment]
@megahead11 The 1.1.1 release is now live, which includes support for negative values (and an optional minimum). Thank you for the suggestion.
