### ISSUE TITLE
Update to v11

### ISSUE THREAD

**Issue by Liviu50** [davelens/fvtt-party-resources#81]
yeah sorry for the ticket :) not to rush or anything but so that i can remember to re download it once you guys are done :) 
keep up the good work!

**Comment by davelens** [comment]
@Liviu50 In this case it's a single guy. 😬

I'm aware of version 11, but haven't even had time to test it out. Pending any mod-breaking issues, it will be updated hopefully over the weekend, along with the recently merged translations.

**Comment by davelens** [comment]
@Liviu50 New release is up, should be smooth sailing for Foundry 11.

**Comment by Liviu50** [comment]
awesome thx for your work and effort dude!
