### ISSUE TITLE
[Issue] Module disables itself and half of the time it says that it cannot be enabled due to issue in required dependency

### ISSUE THREAD

**Issue by Liviu50** [davelens/fvtt-party-resources#82]
Sorry for the long title, but it clears the issue.
So basically most of the time when i log into the campaign i find the module disabled...if i try to "enable" it it says "Cannot enable due to issue in required dependency....BUT if i try to re update all modules (which find no updates) and try again then i can enable it.
This happens each time i log in...altho lately it does not work either way.
Any idea why is this?
If you need any sort of info i will happily oblige.

**Comment by Liviu50** [comment]
Problem seems to be somewhat resolved for now after i reinstalled all the modules, will report if the issue repeats itself after various restarts and sessions.

**Comment by davelens** [comment]
@Liviu50 The only module Party Resources is dependent on is [Azzurite's settings extender module](https://foundryvtt.com/packages/settings-extender). Its latest release was 6 hours ago at the time of writing, and I see it's Foundry 11 compatible now. It might be your issue got resolved when it got updated.

Foundry 11 made a mess of a couple of things, but it's slowly starting to clear up.

**Comment by Liviu50** [comment]
oh i see. makes sense now, kept going off on its own and at times not working anymore.
ill try for a few more session and come back with new info. if the new version resolved everything ill simply closed the issue :) thx.

**Comment by Liviu50** [comment]
ok seems that the module stopped becoming off on its own and work properly after the last update from the settings extender. cheers!
