### ISSUE TITLE
More flexible increment/decrement

### ISSUE THREAD

**Issue by CaelReader** [davelens/fvtt-party-resources#9]
It would be nice for things like a shared party treasury to beable to numerically change the resource on the fly, instead of needing to go in and alter the "default value" field for large changes. An easy approach might be to make the +/- buttons scalable ie, hold shift for increments of 10, ctrl for increments of 100, or something.

**Comment by davelens** [comment]
@CaelReader Thank you for the suggestion. Using hotkeys for different orders of magnitude sounds like a good idea.

No timeline to get it done, but I can probably come up with something. The hardest part might be to give some sort of visual indication which increments are active. Maybe display the jump next to the cursor when the hotkey is pressed while hovering the +/- buttons.

**Comment by davelens** [comment]
@CaelReader This will be included in version 1.1.2. Thank you for the suggestion!
